# {{projectName}} - Agent Rules

> This file is read by AI coding agents (Claude Code, Cursor, Codex, Trae, Cline).
> Managed by [AgentGuard](https://github.com/kentdu1996/agt). Edit `AGENTS.md`; the others are symlinks.

## 📋 Project Context

- **Type**: {{projectType}}
- **Stack**: {{techStack}}
- **Test command**: `{{testCommand}}`
- **Build command**: `{{buildCommand}}`
- **Lint command**: `{{lintCommand}}`

## 🛑 Hard Constraints (NEVER do these)

1. **NEVER** modify files outside `{{projectRoot}}`
2. **NEVER** modify or delete: {{protectedPaths}}
3. **NEVER** hardcode API keys, tokens, passwords — ALWAYS use `process.env.*` (or equivalent)
4. **NEVER** commit `.env`, `*.key`, `*.pem`, or any file matching secret patterns
5. **NEVER** read `.env` files into your context — environment variables are already available
6. **NEVER** install new dependencies without explaining the reason in your response
7. **NEVER** modify database schema, authentication, or payment code without explicit user confirmation
8. **NEVER** refactor unrelated code while fixing a specific bug or implementing a feature
9. **NEVER** rewrite the entire project — make minimal, targeted changes
10. **NEVER** claim a task is complete if tests are failing
11. **NEVER** use mock/fake data and present it as a working implementation
12. **NEVER** run destructive commands without confirmation: `rm -rf`, `git push -f`, `drop database`, etc.
13. **NEVER** auto-update package versions when the user only asked to install one package

## ✅ Required Workflow

1. **Before starting**: read `docs/PROJECT_STATE.md` to understand current state
2. **During work**: make minimal changes, test as you go
3. **After completing**:
   - Run `{{testCommand}}` and verify pass
   - Update `docs/PROJECT_STATE.md` with what changed
   - If you made architecture decisions, append to `docs/DECISION_LOG.md`
4. **When stuck**: ask the user, don't guess by rewriting things

## 🎯 Definition of Done

A task is "done" ONLY when ALL of these are true:
- [ ] Code change is minimal and focused on the request
- [ ] All existing tests still pass
- [ ] New code has corresponding tests (if test framework exists)
- [ ] No new dependencies added without justification
- [ ] `docs/PROJECT_STATE.md` reflects the change
- [ ] No secrets in code
- [ ] No unrelated code modified

## 📁 Project Structure

```
{{projectStructure}}
```

## ⚠️ Risk Areas (require extra confirmation)

{{riskAreas}}

## 🔧 Agent-Specific Notes

### Claude Code
- Use Read before Edit
- Use TodoWrite for multi-step tasks
- Respect `.agentguard/hooks/` configurations

### Cursor / Trae / Cline
- This file is also loaded as `.cursorrules` / `.clinerules` / `.trae/rules.md`

## 📞 Need help?

- Project state: `docs/PROJECT_STATE.md`
- Decision history: `docs/DECISION_LOG.md`
- Project health check: `agt doctor`

---
*Generated by AgentGuard {{version}} on {{date}}. Last edited: {{lastEdited}}*
