# {{productName}}

> {{oneLiner}}
>
> Managed by [AgentGuard](https://github.com/kentdu1996/agt). Edit `AGENTS.md`; other rule files (CLAUDE.md, .cursorrules, .clinerules, .trae/rules.md) are symlinks.

---

## 📌 What this project does

{{ideaExpanded}}

- **Created**: {{date}}
- **Target users**: {{targetUser}}
- **Data storage**: {{dataStrategy}}

---

## 🧱 Tech Stack

{{stackList}}

## ⚙️ Commands

```bash
{{devCommand}}   # dev
{{testCommand}}   # test
{{buildCommand}}   # build
{{lintCommand}}   # lint
```

---

## 🛑 Hard Constraints — NEVER do these

### Universal (all projects)

{{universalNever}}

### Architecture-specific ({{archDisplayName}})

{{archNever}}

### Scene-specific

{{sceneNever}}

---

## ✅ Required Workflow

1. **Before starting** any task: read `docs/PROJECT_STATE.md` for current state
2. **During work**: make minimal changes, test as you go
3. **After completing**:
   - Run `{{testCommand}}` and verify it passes
   - Update `docs/PROJECT_STATE.md` with what changed
   - If you made architecture decisions, append to `docs/DECISION_LOG.md`
4. **When stuck**: ask the user, don't guess by rewriting things

---

## 🎯 Definition of Done

A task is "done" ONLY when ALL of these are true:

### Universal
- [ ] Code change is minimal and focused on the request
- [ ] No new dependencies added without justification
- [ ] No secrets in code
- [ ] `docs/PROJECT_STATE.md` updated

### Architecture-specific
{{archDoneCriteria}}

---

## 📁 Project Structure

```
{{projectStructure}}
```

---

## 📞 Maintained Documents

- `docs/IDEA.md` — your original idea (don't change it)
- `docs/PROJECT_STATE.md` — what's being worked on (update after each task)
- `docs/DECISION_LOG.md` — why decisions were made (append on key decisions)

Project health check: `agt doctor`
Rollback last change: `agt rollback`

---
*Generated by AgentGuard v{{version}} on {{date}}.*
*Architecture: {{archId}} | Stack: {{stackFramework}}*
